spring.application.name=placement-system

spring.datasource.url=jdbc:postgresql://db.dgqvsehwglhisstoogus.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=campusplacement@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=false
spring.thymeleaf.cache=false
spring.devtools.livereload.enabled=true