spring.application.name=placement-system

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
<<<<<<< HEAD
spring.datasource.password=c${SPRING_DATASOURCE_PASSWORD}
supabase.api-key=${SUPABASE_APIKEY}
supabase.url=${SUPABASE_URL}
=======
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
>>>>>>> 2678fe2ab2da9deeeef0a160ba68668ca6ef3498
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.profiles.active=local
spring.flyway.enabled=false
spring.thymeleaf.cache=false
spring.devtools.livereload.enabled=true

<<<<<<< HEAD
server.servlet.session.timeout=5m
spring.devtools.livereload.enabled=true
=======
# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

# Scheduler
spring.task.scheduling.enabled=true
>>>>>>> 2678fe2ab2da9deeeef0a160ba68668ca6ef3498
